### ISSUE TITLE
Open Standard Examples

### ISSUE THREAD

**Issue by mgifford** [canada-ca/Open_First_Whitepaper#1]
Are you looking to specifically list things like:

- [ISO's ODF](https://en.wikipedia.org/wiki/OpenDocument)
- [RDFa](https://rdfa.info/)
- [JSON](https://json-ld.org/)
- [HTML Microdata](https://www.w3.org/TR/microdata/)

If so I assume you're looking for a sample of open standards that apply to the digital space.

**Comment by smellems** [comment]
The idea for the Examples section is to list policies from other countries and public administration and the impact they had.  Same for OSS and Open Source code.

We probably should have a recommendation section.

**Comment by mgifford** [comment]
Ok... So you want links to examples like the ones I've collected here:
https://github.com/mgifford/open-source-contracting

Can you explain the difference between what is intended in the Open Source Software & Open Source Code sections? Code=Software unless I'm missing something.

**Comment by smellems** [comment]
Yes, for Open Standards, I have these I will add:

UK Open standards for government -
 https://www.gov.uk/government/publications/open-standards-for-government

UK Open Standards principles - https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles

TBS Open Data Principles (Use of Commonly Owned Standards) - http://open.canada.ca/en/open-data-principles

**Comment by smellems** [comment]
> Can you explain the difference between what is intended in the Open Source Software & Open Source Code sections? Code=Software unless I'm missing something.

OSS is about the use of OSS by the GC, how it's considered when procuring IM-IT solutions and related services for support and integration.

Open Source Code is releasing code developed by the GC as open source licences.

**Comment by mgifford** [comment]
Could the latter be renamed to "Releasing Open Source Code" or "Releasing to the Open" or something like that?
