### ISSUE TITLE
Incorporate references that connects open culture and "virtue"

### ISSUE THREAD

**Issue by patcon** [canada-ca/Open_First_Whitepaper#102]
There are some real gems in the literature of Commons-based Peer Production, which is the academic term used to describe the sort of open work that is perhaps most readily studied in free software movements. I can't recommend highly enough that people dig into this literature.

For now, I'll just share one of my favourites, and perhaps I'll share some choice quotes when I have time to review :)

- [Quick explainer video of "Commons-Based Peer Production"](https://vimeo.com/174899444)
- [tl;dr of Elinor Ostram's Nobel prize-winning life work on how people manage physical commonses](http://www.onthecommons.org/magazine/elinor-ostroms-8-principles-managing-commmons#sthash.zdmjyt6x.dpbs)
- [Commons-based Peer Production and Virtue](https://www.nyu.edu/projects/nissenbaum/papers/jopp_235.pdf) re: digital commonses. (Yochai Benkler & Helen Nissenbaum)

**Comment by patcon** [comment]
Not the section on "Public Policy"

> A   practical   corollary   of   the   observation   that   _social   and   institutional arrangements  have  the  power  to  shape  human  behavior  and  disposition_,  is  to strive  for  positively  valued  behaviors  and  dispositions  through  purposive interventions  in  these  arrangements. This  ambition  is  not  unprecedented  either in  the  actions  of  political  leaders  or  in  evaluations  of  leaders,  policies  and institutions  by  members  of  the  academy. [...] According  to  Sandel,  such  arguments  would  not  have  been  out  of  place  for  the  environment  in  which  there  was  general  agreement  regarding  the  principle  that:  **“The  public  life  of  a  republic  must  serve  a  formative  role, aimed at cultivating citizens of a certain kind.”** The government was seen to have “a stake in cultivating citizens of a certain kind.”

**Comment by patcon** [comment]
A great quote within the paper itself:

> All around us today are artifacts that were generated in the technological dramas of  their  time:  railways,  canals,  aviation  artifacts,  radios,  and  more.  And  yet  their meaning, together with their location in what was formerly a deeply felt grammar of political action, is utterly lost; in their place is what appears to be nothing more than a material record of “technological progress.” What was once the conscious product of human cultural and political action, passionate and meaningful, is now a  silent  material  reality  within  which  we  lead  our  daily  lives,  mutely  acting  out patterns of behavior that once had obvious connections to the root paradigms of our culture[...]. To  become fully aware of the political circumstances of their lives, new generations of students, at every level of education, must be trained (as Hughes suggests)  to  ‘fathom  the  depth  of  the  technological  society,  to  identify  currents running  more  deeply  than  those  conventionally  associated  with  politics  and economics.’

**Comment by patcon** [comment]
> When a society endorses **social policies** that, for example, offer protection to  whistle-blowers,  provide  tax-credits  for  charitable  donations,  or  generate institutional safeguards against corruption, **it is not shrinking the moral sphere, but  structuring  the  environment  to  lessen  the  burden  of  valued  practices.**  In  a similar way, **commons-based peer production opens a path** previously restricted (by economic cost and industrial organization) to small numbers of professional producers of information, knowledge and culture **to large numbers of ordinary people, enabling them to contribute to the public good in a particular domain.** The path **does not bypass virtuous action, but generates new opportunities for it.**

**Comment by gcharest** [comment]
Thanks for sharing, lots of very deep material there!

**Comment by gcharest** [comment]
Hi @patcon , we'll keep these references in mind but will now close this issue.

Thanks!
