### ISSUE TITLE
Consider recognizing/incorporating definitions of open from Fifty Shades of Open paper

### ISSUE THREAD

**Issue by patcon** [canada-ca/Open_First_Whitepaper#106]
This is a super-thorough academic review of the different ways that the word "open" is used on the internet:

[Fifty Shades of Open](http://firstmonday.org/article/view/6360/5460#p9), First Monday: Peer-Reviewed Journal on the Internet

It defines openness definitions along a spectrum -- seemingly from foundational (but simpler) to more principled and value-based:

> ```
> access > use > transparency > participation > enabling openness > philosophically aligned with open principles
> ```

Still in the process of reading this whole whitepaper (and very excited what I'm seeing so far!), but wanted to share the above in case it aligns :)

**Comment by smellems** [comment]
This paper was mentioned before (#52)

I've looked at it but I'm not sure how to incorporate it.  I want to rewrite the introduction to be more like a business case and introduce the concept of "open" similar to what's in the "Fifty shades of open"

**Comment by patcon** [comment]
Gaaaaah... I am groundhog day :)

Sorry @smellems. Closing this as dup!
