### ISSUE TITLE
Question: Interoperability section

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/Open_First_Whitepaper#11]
For this section I've added a few places where I think we should add sources:
#### Interoperability
The audience involved in digital interactions have not only increased exponentially in number (source?) but have also become more diverse (source?): individuals, businesses, the public, institutions and things all communicate via computer exchanges. These computer exchanges have become an essential conduit, and their overall heterogeneity is an even greater reason for interoperability, meaning the ability to make a variety of information systems communicate with one another. Since this report discusses digital interactions, the expressions "interoperability of information systems (IS)" and "interoperability of information technologies (IT) or information and communication technologies (ICT)" are synonymous.

Also is there a way to plain language conduit, heterogeneity... 

I also think digital interactions also could be confused with User Experience.

I'm going to keep reading. Let me know if this commenting method or the pull requests are working better for the project.

/cc @smellems

**Comment by Acasovan** [comment]
Hey, thanks, and good comments! Will look at language and proper sourcing. We were just trying to get thoughts out of our head. Just updated the README. Please submit a pull request and @smellems and I will do our best to manage. 

Thanks!
