### ISSUE TITLE
Definitions versus Terminology - for citing this as a source

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/Open_First_Whitepaper#110]
Hi all,

Can you clarify if definitions (Section 8) or terminology should be used when citing this document as a source? I know that typically an official Government of Canada policy document uses definitions and that I often share these when people are asking for advice. I did notice though that for the term Open Source Software there is both a terminology explanation and a definition. Perhaps there is a way to streamline this? It might also make the document a quicker read.

Thanks,

Mary Beth

**Comment by MaryBethBaker** [comment]
@smellems I <3 the idea of a standard definitions place in the same place we always look for the terms.

Where we found the term Open source to be better defined was in definitions section because the term in the terminology section said without restriction. But the Open source initiative actually states that the author has the right to set restrictions (section 1 no restrictions, section 4 author defined restrictions if patches are welcome/derived software has different name/version number). Source: https://opensource.org/osd

Would be happy to understand the no restrictions on free cost vs. restrictions on how it's redistributed. I could be wrong or not interpreting this correctly. Happy to hear more.

//cc @RachelMuston in case I got these mixed up.

**Comment by smellems** [comment]
I just moved definitions for open standards, interoperability, source code, free software and open source software to [Definitions](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/en/8_Definitions.md).  I also removed the "without restrictions" when talking about both free and open source software.

**Comment by MaryBethBaker** [comment]
Thanks @smellems!
