### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/Open_First_Whitepaper#116]
You broke a lot of links in existing issues as well as the README.MD on the main page they all go to 404 pages.

**Comment by gcharest** [comment]
Sorry, will have to update them as well. Thanks for pointing it out. We're finalizing a first"official version and aligning with the draft standard that will be shared shortly.

**Comment by gcharest** [comment]
@CalvinRodo Links updated in README.md.

**Comment by gcharest** [comment]
We're now tracking deadlinks in the build.

Closing the issue as it is actively monitored.
