### ISSUE TITLE
Security Classification Clarification

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/Open_First_Whitepaper#117]
Under [Best Practices for Releasing OSS ](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/en/4_Open_Source_Software_Contribution.md#best-practices-for-releasing-oss)  the list of criteria for protected software contains the following line: 

**Information about testing procedures, tests, and audits**

What type of tests does this include and not include. Would automated unit test, automated integration tests, automated End to End tests be included in this list of tests?

**Comment by gcharest** [comment]
Good question, we'll have to expand there. If you have recommended elements, please feel free to add.

I'll be looking at Cyber for more input as well.

**Comment by gcharest** [comment]
Closing to continue discussion on the issue referenced above.
