### ISSUE TITLE
Sentence does not make sense

### ISSUE THREAD

**Issue by swill** [canada-ca/Open_First_Whitepaper#132]
On this page: https://github.com/canada-ca/Open_First_Whitepaper/blob/master/en/2_Open_Standards.md

Section: `Benefits > Interoperability > Independence and substitutability`

The following sentence does not make any sense.

> In the context of enterprise architecture fully under your control, one option to ensure the components' integration is standardization, either of the products directly or within a family of products generally offered by a single vendor.

**Comment by smellems** [comment]
Thanks for flagging this!  The original word in French was `uniformisation`.  Standardization since we're talking about open standards is confusing.

Will review

**Comment by swill** [comment]
I believe what is being communicated is the following, but I will let you confirm that.

> In the context of enterprise architecture fully under your control, one option is to ensure the components have clear integration patterns, either via the products directly or by using a family of products generally offered by a single vendor.

Does this capture what was intended with that sentence?

**Comment by swill** [comment]
@smellems I have created a PR (#133) with the wording I proposed which will close this issue if accepted.  Cheers...
