### ISSUE TITLE
Validation of accuracy

### ISSUE THREAD

**Issue by swill** [canada-ca/Open_First_Whitepaper#135]
In the following section: `Open Standards > Benefits  > Interoperability > Cloud computing`

I don't feel that the following statement is accurate.
> In terms of interoperability, there is no fundamental difference between a conventional infrastructure and a cloud, other than the complexity of the latter and the need to standardize vertical and horizontal components to a much greater degree.

If we refer to the NIST definition of cloud, there are massive differences due to the on-demand nature of the cloud and the availability of APIs and the ability to automate the infrastructure deployments from end to end.  The ability to use tools such as Terraform is an excellent example of the fundamental shift in the delivery and consumption of resources.  Cloud offers the ability to programmatically manage your infrastructure which traditional infrastructure does not.  This is massively important for the ability to standardize usage patterns across the Government of Canada and the ability to provide/publish authorized architectural deployment recipes.

Here is the NIST definition of Cloud:
> The NIST definition lists five essential characteristics of cloud computing: on-demand self-service, broad network access, resource pooling, rapid elasticity or expansion, and measured service.

I recommend everyone read the following (which is where the above comes from): https://www.nist.gov/news-events/news/2011/10/final-version-nist-cloud-computing-definition-published

**Comment by gcharest** [comment]
Hi Will!

Thanks for the input. I agree the sentence is inaccurate and should be
modified. If you have the time to submit a PR with a proposed revised
sentence, I'll review and merge. Otherwise, I'll have a look at how I can
modify it tomorrow.

Guillaume

Le jeu. 9 août 2018 à 16:49, Will Stevens <notifications@github.com> a
écrit :

**Comment by gcharest** [comment]
OK, so here's a first try at conveying the right message:

Change:
> In terms of interoperability, there is no fundamental difference between a conventional infrastructure and a cloud, other than the complexity of the latter and the need to standardize vertical and horizontal components to a much greater degree. 

For:
> In terms of interoperability, the fundamental difference between a conventional infrastructure and a cloud is the complexity of the latter and the need to standardize vertical and horizontal components to a  greater degree in order to maximize the deployment automation of authorized architectural models.

Would love some feedback and wordsmitting if seems more accurate.

Thanks!

**Comment by smellems** [comment]
I think the idea behind saying there is no difference, is that cloud or conventional infrastructure is still a server somewhere. Interoperability between systems (horizontal) still needs to be done with open standards and OSS.  Dependencies on other components of the stack (vertical) still need to be avoided.

Only with cloud, we often don't own or manage the infrastructure, so it's even more important to use open standards and OSS to avoid lock-in to cloud providers as well.

It seems that the characteristics of cloud computing can be achieved whatever infrastructure we use..

**Comment by gcharest** [comment]
Right, I think that's what I'm trying to convey with the slight modification of the sentence. Might have missed the mark there 🤔

**Comment by swill** [comment]
We are looking at this from a consumers perspective though right?  With cloud, the consumer has the ability to control the application architecture, the deployment automation and the actual implementation of what they need in order to operate.  With traditional infrastructure, the user is not able to influence the underlying infrastructure, that is handled by an Ops or IT team.  This means they have to provide a spec of what they need and then it is provisioned (potentially months later).  If they are wrong about what they need, they need to ask for changes, wait forever, rinse and repeat.  

The ability for consumers to leverage cloud enables control over their deployment, especially around automation.  This gives them MUCH more control over how their application architectures are realized in the real world and enables them to operate at the speed of business (and not the speed of IT).  Because automation is possible and recommended through the use of cloud, it then enables a greater possibility of portability because you already have a documented recipe the describes the architecture and deployment.  If you need to change providers, you modify your automation and the problem is solved...

Does that help clarify where I am coming from?

**Comment by swill** [comment]
I will try to find some time today to create a pull request to write up something...

**Comment by gcharest** [comment]
Thanks Will! Will have another look Monday as well on my side.


Le sam. 11 août 2018 09 h 55, Will Stevens <notifications@github.com> a
écrit :
