### ISSUE TITLE
crown copyright notice

### ISSUE THREAD

**Issue by royfielding** [canada-ca/Open_First_Whitepaper#146]
I know this is a pedantic nit (and really none of my business), but I've done so much legal and licensing work that I know this kind of thing needs to be done right, and it is so important to provide a good example to others given the nature of this project …

The copyright notice in LICENSE.md is incorrect because "Government of Canada" is not an entity allowed to own copyright. IANAL, but according to

https://www.canada.ca/en/canadian-heritage/services/crown-copyright-request.html

the correct notice for a crown copyright is

© Her Majesty the Queen in Right of Canada, as represented by the Minister of (legal departmental name), (year of publication).

Obviously, it would be easier to maintain as simply

© The Crown in Right of Canada, (year of publication).

but you might need to get some sort of official approval for that.

BTW, if you have already obtained legal approval for the existing text, please just indicate that and you can close this issue right away. My only concern is that it be an allowed notice. BTW, in the US at least, it is also fine to exclude the legal notice and simply state the license as is, assuming you have no intention of suing for infringement.

YMMV, IANAL, and am not even a Canadian resident.  Cheers.

**Comment by gcharest** [comment]
Thanks for pointing out, will bring this to our team!

**Comment by nschonni** [comment]
I believe the text for https://github.com/wet-boew/wet-boew/blob/master/License-en.txt is an example of on the @pjackson28 got vetted by the TBS lawyers many years ago that mixes the MIT and Crown Copyright

**Comment by royfielding** [comment]
Oh, I need to take some of that back … Canada (unlike the US) does not have a specific form of copyright marking, though it is still [recommended to use the same as other countries](http://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/h_wr02281.html?Open&wt_src=cipo-cpyrght-main&wt_cxt=learn#indicatingCopyright).

The problem with your examples is that the MIT license is assuming US law where it says "The above copyright notice" must be included, and the one line marker chosen that says "Government of Canada" is inconsistent with the actual Crown copyright explained in the text above it.  Personally, I would just remove the confusing Copyright line, or replace it with the suggested text from [www.canada.ca](https://www.canada.ca/en/canadian-heritage/services/crown-copyright-request.html) (since that is consistent with the Copyright Act).

I am resisting the temptation to suggest you just use the Apache License 2.0, which doesn't assume you have a copyright notice line.

**Comment by smellems** [comment]
Thanks @royfielding !

You would not be the first to recommend Apache 2.0 for Government of Canada code :smile:

**Comment by gcharest** [comment]
Indeed, it is recommended both from within partners as well as private
sector.

Le jeu. 4 oct. 2018 15 h 05, Sébastien Lemay <notifications@github.com> a
écrit :

**Comment by gcharest** [comment]
Note that this issue will be incorporated in the draft [Guidelines](https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/publishing-open-source-code.md#appropriate-government-of-canada-copyright-identification) document we're putting together.
