### ISSUE TITLE
Scope of Whitepaper.

### ISSUE THREAD

**Issue by RussellMcOrmond** [canada-ca/Open_First_Whitepaper#15]
In the introduction the paper references the MOU with the UK and the Digital 5 principles.  Those principles extend beyond how government interacts with software, and even includes things such as connectivity.

Is the intention of this whitepaper to include the wider range of issues, or only specifically software issues?

More clearly defining the scope might help answer some of the other questions that have come forward -- for instance, the term "open culture" can mean the culture within government which creates barriers to interacting with open software, it can be open government issues such as proactive disclosure, or it can more broadly be talking about citizens participating with their own culture (Everything from "remix culture" policies, CanCon, telecom/broadcast, etc).

I'm not currently working in government, but have been working with FLOSS (software and policy) since 1992, having consulted to many government departments, participated in consultations, and had clients in other sectors of the economy.  I have experience with many of the barriers that exist within the culture of GoC which has made FLOSS harder to adopt.   I might have useful input into this process, but I need to know the scope of the process to know how to best allocate my time.

As Michael Geist wrote yesterday, there are many GoC processes to be interacting with these days and we each need to pick wisely.   [Too Much of a Good Thing: What Lies Behind Canada’s Emerging Consultation Crisis](http://www.michaelgeist.ca/2017/10/too-much-of-a-good-thing-what-lies-behind-canadas-emerging-consultation-crisis/)

**Comment by Acasovan** [comment]
Thanks for the feedback, Will work on clarifying the scope in the introduction. The scope is broader than open source software. We are trying to think about the entire landscape of open source interactions within the GC. As you noted, there are many process that need to be taken into consideration. This whitepaper is the start of strategy and policy, however, not everything that is included in this doc will necessarily fit into the policy, so this gives us an opportunity to collect ideas, think through our approach, and ensure that we aren't missing any of those potential interactions. Will keep this open until I fix, but wanted to respond back to your question! Hope that helps.

**Comment by RussellMcOrmond** [comment]
My comments to https://github.com/canada-ca/Open_First_Whitepaper/pull/68 are making me think back to this question about scope of the whitepaper.

I was one of the 4 founding members of GOSLING http://www.goslingcommunity.org/ who helped organise the Open Source Solutions Showcase at PWGSC back in 2002.  I haven't been attending the meetups as much recently because many of the participants are focused on opening up government "procurement" such that their FLOSS offerings would get more appropriate consideration.

This wasn't my interest:  even though I was the private-sector representative with 3 public sector co-coordinators back in the beginning, my interest was always in the larger policy implications (How governments regulate and interact with software).  While I believe a FLOSS CMS should have been used for canada.ca,  I'm far more concerned with the underlying policy failures that lead to the Phoenix project.

I met on Sunday with an MP and some people I met in the GOSLING context, and of course Phoenix came up.   We all agreed the problem wasn't with the vendor who just did what was asked of them (knowing ahead of time it was wrong), but the requirements from the government.   Calculating pay should be deterministic, but rather that solving that problem first to create transparent and accountable algorithms (which must be FLOSS to be sufficiently transparent and accountable) the government treated this as if it were a simple "IT" centralisation and outsourcing project that could be used to lay off people within the branches of the departments.   The failure was predicted long before the program was launched as the goals of the project were inappropriate, and the failures could have been far worse.

Governments need to re-think how they deal with software.   Procurement of tangibles and acquisition of intangibles are not the same processes -- I'm not even comfortable using the term "procurement" in the context of software.  When discussing intangibles like software the closest comparison to other intangibles governments work with is policy: rules which computers and humans are intended to obey.  

Contracts and human laws may not be deterministic, and need human intervention when there are conflicting interpretations.  Those policies which are intended to be automated must be deterministic and there should be an English, French and Algorithm translation that are all visible and agreed upon as part of the negotiation.   This should have already been the case with the collective agreements used to calculate public servant salaries, but never was -- and there are many questions that have always existed about the calculations prior to Phoenix as well as currently  (some closer to the issue have suggested that some of the discrepancies in pay happened because Phoenix got the pay correct, but the method previously used was incorrect).


So -- are we trying to get a better CMS used for the inappropriate centralisation of the communications  teams within branches of government (One of the many problems with canada.ca ), or are we trying to avoid constantly repeating policy failures like Phoenix?

**Comment by plantarum** [comment]
@RussellMcOrmond raises some very interesting & important points.   

I'm here to try and reduce the barriers to using, producing and distributing open source code as part of my job as a research scientist. That feels like a very small niche compared to the big picture issues Russel is talking about. I wonder if this is too much ground to cover in one document, or if we need a clearer structure to keep this document from ballooning to an unmanageable size?

**Comment by RussellMcOrmond** [comment]
@plantarum Back when Reg Alcock was President of the Treasury board (we were in touch with him prior to him being appointed to cabinet), the question was often raised what existing policies were acting as barriers to the use, production and distribution of FLOSS by public servants.   We discovered that the problems were often not with documented policy, but with misinterpretation of policies within the specific branches (some accidental, some not so much).

Do you have any existing policies and procedures where you wish there was clarification?  Some problems may be solved simply by providing clarity to existing policies, and don't need new specific open first policies.  There will be other scenarios where open first is required to fix existing policies.  Determining which is which would be useful in determining the scope of this type of whitepaper.

**Comment by Neil-Kemp** [comment]
Part of the challenge is that Policy issue issued without any supporting training or implementation tools. The result is that individuals and departments, usually acting good faith often come to conclusions that are operationally at odd with each other. Attempts in the last few years to “reduce the policy burden actually have, I believe, tended increase the burden as the policy is often less clear then before and requires more effort to understand

 

Neil Kemp

**Comment by RussellMcOrmond** [comment]
@Neil-Kemp Agreed.

Is the goal of this Open First Whitepaper to try to solve a small set of specific problems, or to document a wider range of issues that need to be solved in order to actually implement an "Open First" policy.

It has been suggested that the whitepaper's scope is being narrowed to solve specific problems, but I'm not convinced that is a narrowing of scope but potentially a change in the goals.   I've been watching all the updates to this project, and I'm still not clear on what the overall goal of the whitepaper is.

Was there a specific terms of reference when this project was created?  What are the levels of management who offered staff time to coordinate this expecting as a result?   Apologies that I'm not certain who are the volunteers and who are the staffed project coordinators.

**Comment by plantarum** [comment]
@RussellMcOrmond the most immediate issue I have is that we have vague support for releasing FOSS code/programs, but no guidance on how to secure the appropriate approval. After talking to the key people in my department, if I want to release FOSS code, I'll need approval from my director, our commercialization people, our department IT, legal, and maybe shared services as well. And none of those people have any experience or guidance as to how to handle this. In light of the uncertainty here, "no" is the safest response.

This is what's motivating me to scan through the whitepaper to flag any text that exaggerates or invents risks associated with FOSS: there's a long chain of approvals required for this work, and if anyone in that chain finds something that makes them nervous everything comes to a halt.

So Open First is a lovely idea, but I can't see how to actually get there from here.

**Comment by obrien-j** [comment]
If anyone has any questions about releasing code from GC into the open source community, have them reach out to me john.obrien@tbs.sct.gc.ca (or @cse-cst.gc.ca).

Been there, done that, would be glad to help anyone else through the process. It doesn't need to be that hard.
