### ISSUE TITLE
URL to GC Digital Standards fails: Access Denied

### ISSUE THREAD

**Issue by gnewton** [canada-ca/Open_First_Whitepaper#150]
URL in last paragraph gives a 403: "The GC Digital Standards include a standard to work in the open and make all non-sensitive data, information and source code open for sharing and reuse under an open licence."

https://www.canada.ca/en/government/publicservice/modernizing/government-canada-digital-standards.html

> Access Denied
> You don't have permission to access "http://www.canada.ca/en/government/publicservice/modernizing/government-canada-digital-standards.html" on this server.
> 
> Reference #18.f781bb8.1547827147.c5efaaae

**Comment by gcharest** [comment]
Thanks! Will have a look!

Le ven. 18 janv. 2019 11 h 02, K. Glen Newton <notifications@github.com> a
écrit :

**Comment by gcharest** [comment]
Everything seems to be working now. @gnewton Is it fixed on your side?

**Comment by goatsweater** [comment]
This is working for me now. Maybe it was a GCweb update blip?

**Comment by gcharest** [comment]
I'll close for now. Thanks!
