### ISSUE TITLE
Are public servants allowed to contribute to open source projects?

### ISSUE THREAD

**Issue by ditisalles** [canada-ca/Open_First_Whitepaper#152]
Dear Colleagues,

Thank you for your fantastic effort to develop the Open First Whitepaper.

https://github.com/moja-global is an open source tool used by federal, provincial and territorial agencies in Canada. We would like to explore how to increase collaboration but your paper does not resolve who needs to give permission for public servants to contribute to open source projects (even if there are no security risks.) 

Is there clarity with the administration already? Could you please advise?

Thank you

**Comment by smellems** [comment]
Hi @ditisalles,

The Whitepaper was more high level so we did'nt go into the details of how..

We are now writing Guidance to support the new Directive on Management of IT that says that all source code must be released as OSS.

- [Publishing Open Source Code](https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/publishing-open-source-code.md)
- [Contributing to OSS communities](https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/contributing-to-open-source-software.md)

Short answer is Yes, federal public servants in Canada can contribute to OSS under an OSI approved or a FSF free software licence.

**Comment by ditisalles** [comment]
Thank you for the reply. I indeed found the guidance in the mean time. I will ask Canadian counterparts to get in touch directly.
