### ISSUE TITLE
Licences

### ISSUE THREAD

**Issue by clauded** [canada-ca/Open_First_Whitepaper#16]
Government of Québec has published an open source licence adapted to the canadian context :  https://www.forge.gouv.qc.ca/licence/en/ (https://www.forge.gouv.qc.ca/licence/fr/). The licence has been approved by the OSI and should be of interest to the GC.

**Comment by Acasovan** [comment]
Thanks @clauded see my response to @jpmckinney's discussion on [licensing](https://github.com/canada-ca/Open_First_Whitepaper/issues/31). We have been looking at the Gov of Québec's work as they have been aligning to standards, as you mentioned. When we dig into this, we will be sure to consult both of you. Should be happening soon! Thanks again for sharing.
