### ISSUE TITLE
Open culture?

### ISSUE THREAD

**Issue by boydjaimie** [canada-ca/Open_First_Whitepaper#2]
The section seems to be blank, but it's a critical one! Happy to help with content. Maybe highlight the opportunities that come with working in the open and how to help us get there.

**Comment by Acasovan** [comment]
Sounds great! Would love your input. We are still working to put content in the sections.

**Comment by mgifford** [comment]
It would be great to reference something from the Department of Canadian Heritage, but not sure what that would be. 

There are examples of the [NFB](https://www.nfb.ca/) & [CBC](http://www.cbc.ca/) releasing content on the internet, and was surprised to see this [released under the Creative Commons](https://creativecommons.org/tag/cbc/).

Would be amazing to have a piece that ties in [Remix Culture ](https://en.wikipedia.org/wiki/Remix_culture) as part of what the government is promoting. 

Looking forward to seeing how this section evolves.

**Comment by RussellMcOrmond** [comment]
The Department of Canadian Heritage is dealing with the poor way which Canada has handled convergence.  They are at the level of having to fight back pressure to tax modern communications infrastructure to subsidise outdated distribution mechanisms.

While the OSI 7-layer approach could have been used, where the wired and wireless connectivity would be as neutral as our road transportation system, the government has allowed legacy phone and cable companies far too much control.  While two-way voice (what we previously called telephone) and one-way video communication (what was previously called television) runs "over the top" of layers up to what we call 2.5, lobbying has allowed the term "over the top" to invalidly refer to competition to the incumbents.

I think before we can get to a conversation about "remix culture" we need to fix policies around the underlying communications infrastructure post-convergence, and disallow the legacy broadcast system to control modern communications technology.  Being allowed to legally access the content of our choice on the devices of our choice, and over fully neutral communications networks, is an important first step.

**Comment by mgifford** [comment]
I do think that what @boydjaimie said can work. It can be an **aspirational piece**, focusing on where we want to go and what is possible. But also what is happening despite hurdles that we have imposed on Canadians with outdated ideas of broadcasting. I do think it is worth mentioning that this is bigger than just software (even though this is much more important to our lives than most people realize).

I don't think this paper can wait till we fix copyright or our relationship with our ISPs.

**Comment by RussellMcOrmond** [comment]
@mgifford This is a whitepaper, not specific legislation to be enacted that then "closes" a project.  I don't think we need to pick an order, or only one initiative.

As the government intends to provide more services online -- sometimes replacing offline interactions -- then how the government has regulated digital communications services becomes critical.

The misunderstandings of technology that went into anti-circumvention legislation (added to "copyright" law, but has little to do with copyright) has implications for other uses of technology as well.  The fact that policy makers didn't realise that "encrypted media" was the subject matter of competition law (encryption to tie content to "authorised" devices) and property law (non-owner locks on our communications technology) is the same reason they can't differentiate technological measures uses in online banking compared to the entirely different scenario of online voting.

The same happened with the OSI 7-layers being ignored during convergence -- the policy makers thought it was logical to have the existing phone/cable companies provide Internet, when all these services should have been thought of as "over the top" of basic communications infrastructure provided/regulated similarly to how we provide/regulate surface transportation infrastructure.  Misunderstandings of the understanding technology lead to problematic government policy.


I don't think we are going to "fix" these other problems overnight, but if we continue to initiate changes  as if those problems didn't matter then we will only be making governance worse as more services are moved online.

How are we going to reconcile a theoretical ability to "remix" content released by the government with the fact that children are being told that sharing-is-stealing when we should be sticking with sharing-is-caring until they are old enough for extremely abstract concepts like "copyright" could be understood (recognising that most adults -- including most politicians and policy makers -- don't understand copyright)

https://fairduty.wordpress.com/2017/10/16/how-canadian-education-really-hurts-creators/

**Comment by smellems** [comment]
We now have initial text in the open culture section
