### ISSUE TITLE
Great start.   

### ISSUE THREAD

**Issue by KristinaJensen** [canada-ca/Open_First_Whitepaper#29]
May I respectfully suggest switching the personalization of the piece (the word "our") in the opening for a more generic approach, to establish a rapport with the reader and then bring them with words like "our".  
Perhaps 'current' is a substitute.  Sorry for wordsmything...it's my job - it's my curse. :)

**Comment by Acasovan** [comment]
Thanks Kristina, that's my fault. Right now we are trying to do our best to get our thoughts out. Working in the open isn't always ideal for that reason, but it's a principle and practice that we are committed to! Especially for this project. I promise when we move from DRAFT, we will clean up all the language!
