### ISSUE TITLE
Don't hate me  :)

### ISSUE THREAD

**Issue by KristinaJensen** [canada-ca/Open_First_Whitepaper#30]
TEXT READS:  
 Hopefully, the whitepaper will lead to a number of strategic changes to the Government of Canada (GC) approach, including a Information Management - Information Technology (IM-IT) digital strategy that favors the use of open standards as well as OSS and that this would be a central part of the GC digital policy. 

SUGGESTION IMPROVEMENTS:
...including an Information - Information Technology (not "a")/ favour - Canadians use UK spelling. Add a comma after standards./And this would be...becomes "which would become.

**Comment by smellems** [comment]
Hi @KristinaJensen thanks for your interest and suggestions!

Are you able to make pull requests so we can better see your proposed changes?  We will most likely accept them :smile:

**Comment by KristinaJensen** [comment]
Hi Sébastien. Thanks for being such a good sport!  I am a newbie with GITHUB, but will try and use it properly, LOL.  Let me go back in and see what havoc I can wreak!  ☺  Cheers. k
