### ISSUE TITLE
Translation Services for Markdown and/or Restructured Text.

### ISSUE THREAD

**Issue by petersilva** [canada-ca/Open_First_Whitepaper#32]
Getting stuff in the other official language is important, and will be an issue once the draft is complete.
You can't just use Google or other translations for this sort of precise documentation with legal meanings, sometimes human expertise is really needed.  For another project last fiscal year, I tried using the government-wide translation service, but they don't accept restructured text or markdown. They accept industry standard formats such as Word documents, but just refuse .rst or .md's.  translating between formats is likely to be problematic, but they just aren't equipped to deal with github style formats right now.

**Comment by Acasovan** [comment]
Thanks for your comment! Once we have a good working draft, that is more complete we will work to translate. As we are working in the open on this initial draft, we are encouraging everyone to write in their language of preference.

**Comment by petersilva** [comment]
From the response, I gather that this is understood to be a problem that you want to deal with later.  That's fine, and should result in putting a ticket in a pending state, or some other state to indicate it will be dealt with later. Closing an issue should only be done if it has been resolved, which the response clearly indicates is not the case. Closing an issue without resolving is insulting, disrespectful, that tells people that it is a waste of time to submit them if they just get closed without any attempt at resolution. If you actually want feedback, don't do that.
