### ISSUE TITLE
Open Markets

### ISSUE THREAD

**Issue by mgifford** [canada-ca/Open_First_Whitepaper#38]
I'd like to write up something about 

https://www.drupalgovcon.org/

or 

http://drupalgov.org/

to highlight the effect of building an ecosystem of vibrant open source companies that can serve the needs of government departments. A huge part of this is government involvement in open source events like:

http://www.drupalnorth.org/

**Comment by mgifford** [comment]
Changing title because it is more about supporting the growth of a market to serve government.

**Comment by Acasovan** [comment]
Mike, I think this would be a good idea for the case study section. As per the ReadMe, please add as a pull request, and we will add in.
