### ISSUE TITLE
Introduction getting long?

### ISSUE THREAD

**Issue by mgifford** [canada-ca/Open_First_Whitepaper#42]
I do think it might make sense to edit down the introduction. 

I was comparing it with:
  https://github.com/DISIC/foss-contrib-policy-template/blob/master/FOSSPolicyTemplate.md

I like their objectives:

> PUBLIC_ADMINISTRATION's goals in releasing this policy are:
>     Comply with regulations
>     Collaborate between national and international public administrations
>     Engage with existing communities
>     Foster economic growth
> 
> The objective of this policy is to allow PUBLIC_ADMINISTRATION to embrace open source software development without compromising its core interests and information security, following the communities’ best practices and in the respect of all stakeholders.
> 
> Globally this policy proposes to:
>     Allow civil servants and subcontractors to contribute and release open-source projects
>     Share best practices to collaborate and engage with communities
>     Provide support and assistance

Although I'd prefer if it was stronger. "Allow civil servants ..." should be "Encourage civil servants ..."

With the Canadian introduction though I don't know that the section on 'Cloud computing' really needs to be there. Obviously this fits within cloud computing. Not sure why it needs to be defined here.

**Comment by smellems** [comment]
I agree it's getting long.  We probably don't need to list and define the digital principles here since they will be published elsewhere.  I added lots of things under Interoperability (including cloud), maybe this should be in the Open Standards section since that's what it's about really.

**Comment by Mateofortin** [comment]
Agreed, maybe a simple reference to the digital principles if needed as listing them will probably make it a nightmare to maintain...

**Comment by smellems** [comment]
The section on Interoperablility was moved to Open Standards.  I just removed the digital principles and replaced them with a link to the current draft version.
