### ISSUE TITLE
Open Markets & D5

### ISSUE THREAD

**Issue by mgifford** [canada-ca/Open_First_Whitepaper#5]
I would love governments to start thinking about ways to enhance an open source ecosystem. I think this will both bolster SME's in participating countries and build more space for innovation across the board.

What I'm having trouble is finding references to the D5 Principle of Open Markets. I got to this D5 Charter:
https://www.ict.govt.nz/assets/Uploads/D5Charter-signed-accessible.pdf

And this wiki page:
https://en.wikipedia.org/wiki/Digital_5

But there just isn't enough about this. Like that you've described "Paying for Open" as a critical part of this.

**Comment by Acasovan** [comment]
Yeah, that's all I could find too. Will ask around.

**Comment by mgifford** [comment]
Btw, if you want the text of that PDF, I put it into a little html file here https://github.com/mgifford/d5-charter

I hate PDFs.  Inaccessible most of the time and just bloody annoying the rest.
