### ISSUE TITLE
Related resource: Fifty Shades of Open

### ISSUE THREAD

**Issue by patcon** [canada-ca/Open_First_Whitepaper#52]
Nice! Just found this repo!

I know of a review paper that some academic friends working in open source have found to be very useful. Thought it might be of interest to those working on this project, perhaps to help disambiguate. (I still need to read the resource full myself though!)

http://journals.uic.edu/ojs/index.php/fm/article/view/6360/5460

> # Abstract
>
> Open source. Open access. Open society. Open knowledge. Open government. Even open food. The word “open” has been applied to a wide variety of words to create new terms, some of which make sense, and some not so much. This essay disambiguates the many meanings of the word “open” as it is used in a wide range of contexts.

**Comment by gcharest** [comment]
Thank you for your contribution! We'll close the issue for now but keeping it in mind as a reference.
