### ISSUE TITLE
Everything an open source maintainer might need to know about open source licensing

### ISSUE THREAD

**Issue by nschonni** [canada-ca/Open_First_Whitepaper#56]
Might be some stuff in here that could help https://ben.balter.com/2017/11/28/everything-an-open-source-maintainer-might-need-to-know-about-open-source-licensing/

/cc @benbalter

**Comment by Acasovan** [comment]
Thanks @nschonni there has been a lot of discussion around the use of licenses. We have been working on this as part of the creation of a digital policy, however, I think that it warrants putting a workshop together. I will organize for the new year. Let me know if you think of people who should be invited.

**Comment by jvanulde** [comment]
O'Reilly Press has a good book entitled: "Understanding Open Source and Free Software Licensing: Guide to Navigating Licensing Issues in Existing & New Software" that I have used in the past to get people up to speed on the topic.

**Comment by gcharest** [comment]
Hi! We'll close this issue but keep the information in mind to address issues #31 and #4.
