### ISSUE TITLE
Governance and timelines

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/Open_First_Whitepaper#58]
Hi @Acasovan,

I noticed that there are no obvious timelines for EARB or Community software submissions and reviews. It would be good to have a sense of how long the process should take or how long a expert/community member is required to wait, especially given that the pace of software moves quite frequently and new requirements for different types of software often appear within their own contexts and with their own timelines.

Mary Beth
//cc @laurawesley

**Comment by Acasovan** [comment]
Thanks @MaryBethBaker for the feedback. I'm going to be working on a terms of reference for the communities of practice, that will probably be a better place to put those timelines. That said, going to EARB is going to depend on the tool and the community. I will put in there the timeline for submitting a request though, and what that process entails.

**Comment by MaryBethBaker** [comment]
I see this as also an opportunity to understand for people using Open Source the context of EARB, some of it's benefits and potential limitations. I am curious about the background of individuals on this board being able to make decisions about Open source tools that are very niche and domain specific i.e. GIS programs, scientific programs, engagement platforms, Statistical packages such as R. I have to say that a community approach to this board might help with the make up of this group. I don't know if there are already standing terms of reference, if employment in the public service is required... these details would help me to understand if my tool is going to be reviewed by an individual with the ability to understand the complexity of various domains of work.

I am also curious about how something as simple as a dependency such as nokogiri, Ruby or other open source library will be covered in this process. Since root or admin access is often required to proceed with projects that require these tools, I have often gotten stuck just thinking about getting senior management approval for tools. Especially if as a project is underway it is found that a different version of the tool is required. 

My example is trying to clone and re-use the @cds-snc's website. I needed a gem called Bundler, which required Ruby and Ruby gems. A specific version of Ruby (2.1.8?) and Nokogiri were required to get Homebrew and Bundler working just on a local machine.

Let me know if you need more context.

Thanks,

Mary Beth

**Comment by MaryBethBaker** [comment]
FYI - I see based on a tweet by Alex Benay that this group meets weekly.

**Comment by gcharest** [comment]
Hi @MaryBethBaker ! This topic should most likely be addressed by the Enterprise Architecture team at TBS and kind of falls outside the content of the whitepaper.

Please also consult the Open Source Advisory Board About [document](https://github.com/canada-ca/OS-Advisory_Conseil-SO/blob/master/1_About.md) and [repo](https://github.com/canada-ca/OS-Advisory_Conseil-SO) for more details about governance.
