### ISSUE TITLE
one or two whitepapers

### ISSUE THREAD

**Issue by plantarum** [canada-ca/Open_First_Whitepaper#60]
The first paragraph of the introduction refers to 'a whitepaper' and 'the whitepaper', in reference to something the Treasury Board is doing, or will be doing.

The second paragraph refers to 'this whitepaper', in reference to this repository.

Are these the same thing? As written, it's not clear if this repository is the whitepaper referred to in the first paragraph, or if it is only something that will inform some other whitepaper that TB is preparing elsewhere.

**Comment by smellems** [comment]
There is only one Whitepaper on Open and it's this one on Github.

**Comment by plantarum** [comment]
Ok, I submitted a pull to refer to "this" rather than "the", so the first two paragraphs will be consistent.
