### ISSUE TITLE
what is the point of the assessment template?

### ISSUE THREAD

**Issue by plantarum** [canada-ca/Open_First_Whitepaper#69]
What is the purpose of the template? Is it for adopting software as users, or for providing code as developers? Some of the criteria only make sense in one context or the other. For example, the language used, or if the code base is accessible to a search engine, is irrelevant to users.

Also, for some of us our work may involve developing new software for which there is not, and may never be, a robust or diverse community. If that is seen as a requirement for working with a open source software, it would be a barrier to developing and sharing R packages for specialized analyses. 

And I'm sure many of the programs that I interact with daily haven't had substantial development in years - not because they're obsolete, but because they are effectively "complete".

**Comment by sajattack** [comment]
Are citizens meant to contribute assessments in the form of the template to suggest open source software?

**Comment by sajattack** [comment]
What's the best way for citizens to get involved with this project?

**Comment by nschonni** [comment]
I'd like to suggest with that we split the "assessment" portion of this project into its own repo rather than lumping it in with the whitepaper content.

**Comment by smellems** [comment]
We will split them up 😀. I'm Just waiting to see where best to put it.  Probably be moving Assesments and Open Resource Exchange

**Comment by nschonni** [comment]
Maybe just `canada-ca/Open_Source_Assessments`

**Comment by smellems** [comment]
Assessments and Open_Resource_Exchange section moved to new Repo: https://github.com/canada-ca/ore-ero

Will probably create Jekyll site in /docs..  Will close this.  Please open issues in new repo
