### ISSUE TITLE
Owncloud vs Nextcloud

### ISSUE THREAD

**Issue by sajattack** [canada-ca/Open_First_Whitepaper#74]
I see in the [Open Source Software section](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md) of this document that you're using OwnCloud for document sharing. Might I suggest you take a look at NextCloud? The original founder of OwnCloud left the company to create NextCloud. It has more features, and it is more open (no closed-source version). Also it has security improvements. A full comparison can be found [here](https://civihosting.com/blog/nextcloud-vs-owncloud/).

**Comment by smellems** [comment]
Thanks! The list of preferred OSS was removed from the document and will be developed somewhere else.  Maintaining a list is one of the Actions.  Selection will be guided by working groups and EARB process.

**Comment by sajattack** [comment]
What's the best way to contribute to this project?

**Comment by mgifford** [comment]
They take PRs with improvements. Also comments like this helps.

**Comment by smellems** [comment]
Will close this for now. A new repo was created for the Open Resource Exchange and software assessments.

https://github.com/canada-ca/ore-ero
