### ISSUE TITLE
Expand "8_Definitions.md"

### ISSUE THREAD

**Issue by cgendreau** [canada-ca/Open_First_Whitepaper#78]
I would like to see very basic definitions to help people new to the subject (even if they are already defined on Wikipedia).
- Licence
- Copyright
- Copyleft
- Intellectual property

The section [3_Open_Source_Software.md#terminology](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md#terminology)
should probably point directly to [8_Definitions.md](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/8_Definitions.md)

**Comment by mgifford** [comment]
Sounds good.  Need something beyond a quick summary of
- https://en.wikipedia.org/wiki/Software_license
- https://en.wikipedia.org/wiki/Copyright
- https://en.wikipedia.org/wiki/Copyleft
- https://en.wikipedia.org/wiki/Intellectual_property

**Comment by smellems** [comment]
I added the definitions you suggested.  Not sure if we should remove all definitions from the Whitepaper and expand in the definitions or if definitions section should be just short definitions.

**Comment by Acasovan** [comment]
Hey, I think that it will have to be a mix. All things that need to be defined should for sure go into the definitions section, but some sections might be better understood of the definitions are there. Like you said, keeping them short within the whitepaper makes sense for sure! Bref, both :)
