### ISSUE TITLE
Need for pre-certified list of OSS support suppliers, similar to the Software Licensing Supply Arrangement (SLSA)

### ISSUE THREAD

**Issue by remyb2canada** [canada-ca/Open_First_Whitepaper#80]
Regarding section [Open Source Software / Best Practices for OSS use](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md#best-practices-for-oss-use)

Another challenge in the adoption of OSS in government is the procurement process to obtain a support provider. This means going through an RFP process which would act as a deterrent for most and have them buy a close-source license from products in the [SLSA list ]((http://logiciels-software.tpsgc-pwgsc.gc.ca/aaall-slsa/gnrx-gnrl-eng.cfm) instead.  Products in the SLSA list already have support agreements in their licenses and makes it more timely to get a product with support in an organization.

This is especially true for organizations with low capacity to provide the support in house and wanting to only consume the OSS with an assurance that they can get the necessary support if need be. 

It would be beneficial for the GC to include a list of pre-certified OSS support  vendors in the SLSA list that can easily be picked, without a lengthy process. This may also add the benefit of allowing niche players to enter the GC market. OSS support providers would then essentially act as the gateway and channel the organizations' needs and issues back to the community for the OSS evolution.

**Comment by RussellMcOrmond** [comment]
I'll reference the note I made in https://github.com/canada-ca/Open_First_Whitepaper/issues/77#issuecomment-351077189

While a list of specific software projects which other departments are already using is helpful,  I believe a pre-certified list of software licenses would also be very helpful.  With FLOSS the obligations on the government are not so much tied to the software or a vendor but the license, and commercial FLOSS support should be considered a separate contracting process from acquisition of the specific FLOSS software.

The bundling of acquisition of the software with support has been one of the many ways that non-FLOSS vendors have been able to block the use of FLOSS in some branches.   The existing availability of known quality commercial support for FLOSS should be a consideration when comparing FLOSS projects that offer similar functionality, but the acquisition of the FLOSS should never be subjected to an RFP.

Note: While the same revision of FLOSS licenses are often used by many software projects (more than can be counted in the case of the GPL v2 and v3), non-FLOSS software often has multiple license revisions that need to be vetted for the same software.

Also, some branches separate licensing fees from software support in budgets, which has been used to block hiring FLOSS support companies (which is one budget) from getting the same support in the form of an "additional license fee" from non-FLOSS vendors.   I ran into this problem many times when on government contracts over the decades.

**Comment by sboots** [comment]
> The bundling of acquisition of the software with support has been one of the many ways that non-FLOSS vendors have been able to block the use of FLOSS in some branches.

@RussellMcOrmond these are really important points.

**Comment by mgifford** [comment]
I'm with @RussellMcOrmond on this. Although maybe rather than a "pre-certified OSS support vendors" the government could simply create a list of Canadian companies who have demonstrated leadership in various open source projects. There are a bunch of innovative Canadian companies who have contributed their time and energy into improving a commons.  This should be acknowledged. If this can be easily added to, then this might also encourage a richer open ecosystem in Canada.

**Comment by Acasovan** [comment]
K, will add this to the outcomes for the Open Resource Section. We need to get these working groups started ASAP!

**Comment by nschonni** [comment]
The software assessment/list stuff has moved to https://github.com/canada-ca/ore-ero

**Comment by nschonni** [comment]
Sorry, re-open if you think the paper needs to talk about the concept of the list of providers
