### ISSUE TITLE
Who is the intended audience? 

### ISSUE THREAD

**Issue by massierick** [canada-ca/Open_First_Whitepaper#88]
Just curious - who is the target audience for this? And is there a desire to make the content more "plain-language"?

I've noticed a mix of writing styles in the document so far, and am curious to see if anyone thinks it would be worth doing a read through for grammar/stylistic consistency, and to make the language simpler and easier to understand. If this is intended to be posted to Canada.ca, this would be a good step in making it meet the content guidelines. 

Great work on this document, it's a great idea, and I'd love to help out in some small way, even if it's just simple wording/grammar reviews.

**Comment by Acasovan** [comment]
Hey! Thanks for the feedback @massierick We do want to make the doc more consistent than it is now, but we are working on getting all the necessary content in first. This paper is both informational and the items in the open resource exchange will also be added to an open source standard (in the policy sense). 

Thanks for your offer to help! If you notice grammatical issues, please adjust via a pull request. That said, when we are closer to a final version, we'll reach out for sure.
