### ISSUE TITLE
Open Source Inventory

### ISSUE THREAD

**Issue by Acasovan** [canada-ca/Open_First_Whitepaper#89]
Hey @smellems @gabrielcossette. I know that we have info GCPedia, but can we start to put an inventory together of Open Source projects in the #GC within the paper?

**Comment by ToferC** [comment]
We've started to pull a list together on the canada-ca repo. I'll hunt down
the link.

**Comment by ToferC** [comment]
Here you go: https://github.com/canada-ca

**Comment by nschonni** [comment]
Although GitHub specific, this one gets a little more attention https://github.com/github/government.github.com/blob/10d6b823e5e7313f07684b5a74adbf717a0bcbba/_data/governments.yml#L99

**Comment by smellems** [comment]
Yes I will see what I can get on the Software_Catalog pages on GCpedia.  We should do this on the [Open Resource Exchange](https://github.com/canada-ca/ore-ero)

**Comment by gabrielcossette** [comment]
Great idea! I've been adding GC OSS projects on the "GitHub" GCpedia page so far.

So there are two suggestions. Either the **welcome** or **ore-reo** repo. Which one should we pick?

For the format, we could take the same one as GCpedia to begin with, for example:
**Department Code | Project Name | URL | Licence**

**Comment by nschonni** [comment]
Ideally we'd have something like this https://usdigitalregistry.digitalgov.gov/
Don't think this is the right one https://github.com/gsa-data/usdigitalregistry.digitalgov.gov but the code is around somewhere and mainly powered by Swagger

**Comment by gcharest** [comment]
Hi everyone! The pilot/prototype of this issue is located at this [link](https://canada-ca.github.io/ore-ero/)
