### ISSUE TITLE
lower user familiarity with OSS software packages

### ISSUE THREAD

**Issue by mgifford** [canada-ca/Open_First_Whitepaper#92]
> Of course, a business or government organization must balance these benefits against several drawbacks, such as lower user familiarity with OSS software packages.

https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md

I think that the question really comes down to which users have lower familiarity with OSS. If we're just talking about the existing staff that should be pointed out. Certainly with the broad adoption of OSS software on the internet, finding people with knowledge of particular proprietary experience logically would be less common.

**Comment by gcharest** [comment]
Hi @mgifford , we'll close this issue as we have incorporated material to this in the section [Training and Support](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/en/3_Open_Source_Software.md#training-and-support)
