### ISSUE TITLE
République française : Politique interministérielle de contribution aux logiciels libres 

### ISSUE THREAD

**Issue by mathieugp** [canada-ca/Open_First_Whitepaper#94]
La DINSIC vient de lancer un appel à commentaire (ouvert jusqu’au 6 janvier 2018) sur une politique interministérielle de contribution aux logiciels libres :

https://github.com/DISIC/politique-de-contribution-open-source
https://disic.github.io/politique-de-contribution-open-source/

The French DINSIC just issued a call for comment (open until January 6, 2018) on a Free and Open Source Software Contribution Interministerial Policy.

**Comment by gcharest** [comment]
Bonjour @mathieugp, merci pour votre contribution!

La France a terminé la phase de consultation et a officiellement publié sa politique!

**Comment by mathieugp** [comment]
Oui, la politique française est publiée et celle de la Ville de Montréal également !

Je travaillais justement aujourd'hui même sur une critique constructive de la politique de la Ville de Montréal dans le Wiki de FACiL : 

https://wiki.facil.qc.ca/view/Utilisateur:Mathieugp/Brouillons/Commentaires_sur_la_Politique_sur_l%27utilisation_et_le_d%C3%A9veloppement_des_logiciels_et_du_mat%C3%A9riel_libres_de_la_Ville_de_Montr%C3%A9al

Plus tard (peut-être la semaine prochaine) je vais soumettre ça au CA de FACiL et ensuite nous publierons quelque chose d'officiel qui sera envoyé à la Ville de Montréal, à nos membres et nos adeptes. :-)

**Comment by mathieugp** [comment]
J'arrive un peu tard, mais je tenais à signaler que FACiL a publié sa critique constructive de la politique de la Ville de Montréal le 11 juin dernier :

https://facil.qc.ca/comment-polmtl-libre

**Comment by gcharest** [comment]
Merci! Ça m'avait complètement échappé!

Guilllaume
