### ISSUE TITLE
Strategy for managing open source code

### ISSUE THREAD

**Issue by LaurentGoderre** [canada-ca/Open_First_Whitepaper#96]
Just like at the beginning of the GC Government Online initiative, there starts to be a fragmentation of the open source code we release. I believe the GC needs a strategy to ensure that we can easily access all the OSS code we release and ensure that we keep ownership of that code as part of regular staff turnover, etc...

As part of this strategy we should ensure we are meeting the spirit of the Communications Policy and the [Technical specifications for social media accounts]https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program/technical-specifications/social-media-accounts.html

The strategy should also how be safeguard, not just the code but the history of the project (Issues, Wiki, Releases, etc...) through backup, security, and identity management.

**Comment by obrien-j** [comment]
Ownership of open source code seems like perhaps not the correct word to use...

I just posted a comment on rlier's pull request, but I've been toying with standing up a https://code.canada.ca reusing the https://code.gov as a way to do better aggregation of the work that's being done... If others are interested, i'm sure we could work something out. ;) (no time!!)

For the time being, i'd worry less about the control aspects and more about getting depts in the habit of writing and releasing code. Lessons learned will come as we go, and will be shared freely!

**Comment by LaurentGoderre** [comment]
I'm not proposing to bottleneck or control the creation of open source repos, far from it. A centralized model would stifle innovation. I do think however that we need measure to safeguard the code we put out and also make the code we release discoverable.

As for lessons learned, we already learned many lessons when we went online and these lessons should not be overlooked. The more we wait, the more work it will be.

**Comment by Acasovan** [comment]
Hey, @smellems is working on this, and has already set up another repo for the open resource exchange. Check out the project in this repo to see what tasks are underway.

**Comment by gcharest** [comment]
Hi @LaurentGoderre Thanks for your contribution. We do want to ensure that there is global visibility as to where OSS projects are hosted but we also want to avoid a bottleneck and increased bureaucracy in releasing projects.

The angle we took was to start working on a [Open Resource Exchange](https://canada-ca.github.io/ore-ero/home.html) where we can point to all the various projects released openly without prescribing a specific hosting provider. The challenge is going to be the capture of all these initiatives and making sure the information is kept to date.
